[general]
host = "0.0.0.0"
port = 6432
connect_timeout = 3000
idle_timeout = 30000
server_lifetime = 86400000
ban_time = 60
autoreload = 15000
worker_threads = 4
admin_username = "admin"
admin_password = "admin"
# Enable HTTP Admin API on port 9930 for zero-downtime pool management
admin_host = "0.0.0.0"
admin_port = 9930

[pools.postgres]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.postgres.users.0]
username = "postgres"
password = "postgres"
pool_size = 10

[pools.postgres.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "postgres"

[pools.tansu_identity]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_identity.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_identity.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_identity"

[pools.tansu_tenant_e2e_server_ank]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_e2e_server_ank.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_e2e_server_ank.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_e2e_server_ank"

[pools.tansu_tenant_nightly_server_ank]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_nightly_server_ank.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_nightly_server_ank.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_nightly_server_ank"

[pools.tansu_tenant_obs_smoke_1760559640]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1760559640.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1760559640.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1760559640"

[pools.tansu_tenant_obs_smoke_1760565020]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1760565020.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1760565020.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1760565020"

[pools.tansu_tenant_tc_traces_fd333f61236341d2a91ea9f722e578c4]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_tc_traces_fd333f61236341d2a91ea9f722e578c4.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_tc_traces_fd333f61236341d2a91ea9f722e578c4.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_tc_traces_fd333f61236341d2a91ea9f722e578c4"

