[general]
host = "0.0.0.0"
port = 6432
connect_timeout = 3000
idle_timeout = 30000
server_lifetime = 86400000
ban_time = 60
autoreload = 15000
worker_threads = 4
admin_username = "admin"
admin_password = "admin"

[pools.postgres]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.postgres.users.0]
username = "postgres"
password = "postgres"
pool_size = 10

[pools.postgres.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "postgres"

[pools.tansu_identity]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_identity.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_identity.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_identity"

