[general]
host = "0.0.0.0"
port = 6432
connect_timeout = 3000
idle_timeout = 30000
server_lifetime = 86400000
ban_time = 60
autoreload = 15000
worker_threads = 4
admin_username = "admin"
admin_password = "admin"

[pools.postgres]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.postgres.users.0]
username = "postgres"
password = "postgres"
pool_size = 10

[pools.postgres.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "postgres"

[pools.tansu_identity]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_identity.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_identity.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_identity"

[pools.tansu_tenant_e2e_server_ank]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_e2e_server_ank.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_e2e_server_ank.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_e2e_server_ank"

[pools.tansu_tenant_nightly_server_ank]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_nightly_server_ank.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_nightly_server_ank.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_nightly_server_ank"

[pools.tansu_tenant_obs_smoke_1758882258]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758882258.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758882258.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758882258"

[pools.tansu_tenant_obs_smoke_1759064471]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759064471.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759064471.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759064471"

[pools.tansu_tenant_obs_smoke_1759066680]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759066680.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759066680.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759066680"

[pools.tansu_tenant_obs_smoke_1759067670]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759067670.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759067670.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759067670"

[pools.tansu_tenant_obs_smoke_1759070052]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759070052.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759070052.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759070052"

[pools.tansu_tenant_obs_smoke_1759070501]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759070501.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759070501.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759070501"

[pools.tansu_tenant_obs_smoke_1759077014]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759077014.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759077014.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759077014"

[pools.tansu_tenant_obs_smoke_1759077702]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759077702.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759077702.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759077702"

[pools.tansu_tenant_obs_smoke_1759078299]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759078299.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759078299.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759078299"

[pools.tansu_tenant_obs_smoke_1759085158]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759085158.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759085158.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759085158"

[pools.tansu_tenant_obs_smoke_1759085420]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1759085420.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1759085420.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1759085420"

