[general]
host = "0.0.0.0"
port = 6432
enable_prometheus_exporter = true
prometheus_exporter_port = 9930
connect_timeout = 3000
idle_timeout = 30000
server_lifetime = 86400000
ban_time = 60
autoreload = 15000
worker_threads = 4
admin_username = "admin"
admin_password = "admin"

[pools.postgres]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.postgres.users.0]
username = "postgres"
password = "postgres"
pool_size = 10

[pools.postgres.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "postgres"

[pools.tansu_identity]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_identity.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_identity.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_identity"

[pools.tansu_tenant_e2e_server_ank]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_e2e_server_ank.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_e2e_server_ank.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_e2e_server_ank"

[pools.tansu_tenant_nightly_server_ank]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_nightly_server_ank.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_nightly_server_ank.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_nightly_server_ank"

[pools.tansu_tenant_obs_smoke_1758527975]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758527975.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758527975.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758527975"

[pools.tansu_tenant_obs_smoke_1758529896]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758529896.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758529896.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758529896"

[pools.tansu_tenant_obs_smoke_1758534793]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758534793.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758534793.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758534793"

[pools.tansu_tenant_obs_smoke_1758536908]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758536908.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758536908.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758536908"

[pools.tansu_tenant_obs_smoke_1758537208]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758537208.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758537208.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758537208"

[pools.tansu_tenant_obs_smoke_1758542219]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758542219.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758542219.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758542219"

[pools.tansu_tenant_obs_smoke_1758542921]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758542921.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758542921.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758542921"

[pools.tansu_tenant_obs_smoke_1758549905]
pool_mode = "transaction"
query_parser_enabled = true
primary_reads_enabled = true
load_balancing_mode = "random"

[pools.tansu_tenant_obs_smoke_1758549905.users.0]
username = "postgres"
password = "postgres"
pool_size = 20

[pools.tansu_tenant_obs_smoke_1758549905.shards.0]
servers = [["postgres", 5432, "primary"]]
database = "tansu_tenant_obs_smoke_1758549905"

