// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TansuCloud.Gateway.Data;

#nullable disable

namespace TansuCloud.Gateway.Data.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    partial class PolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TansuCloud.Gateway.Data.ObservabilitySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("SamplingPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Component")
                        .IsUnique()
                        .HasDatabaseName("ix_observability_settings_component");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_observability_settings_enabled");

                    b.ToTable("ObservabilitySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Component = "prometheus",
                            Enabled = true,
                            RetentionDays = 7,
                            SamplingPercent = 100,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Component = "tempo",
                            Enabled = true,
                            RetentionDays = 7,
                            SamplingPercent = 100,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Component = "loki",
                            Enabled = true,
                            RetentionDays = 7,
                            SamplingPercent = 100,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TansuCloud.Gateway.Data.PolicyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_gateway_policies_enabled");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_gateway_policies_type");

                    b.HasIndex("Type", "Enabled")
                        .HasDatabaseName("ix_gateway_policies_type_enabled");

                    b.ToTable("gateway_policies");
                });
#pragma warning restore 612, 618
        }
    }
}
