name: build-citus-pgvector

on:
  push:
    branches: [ master ]
    paths:
      - 'dev/Dockerfile.citus-pgvector'
      - '.github/workflows/build-citus-pgvector.yml'
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dev/Dockerfile.citus-pgvector
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/citus-pgvector:pg17
            ${{ secrets.DOCKERHUB_USERNAME }}/citus-pgvector:pg17-${{ github.sha }}
          provenance: false
