name: UI E2E (Playwright)

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose up (infra)
        run: |
          echo "POSTGRES_USER=postgres" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=postgres" >> $GITHUB_ENV
          echo "PGCAT_ADMIN_USER=admin" >> $GITHUB_ENV
          echo "PGCAT_ADMIN_PASSWORD=admin" >> $GITHUB_ENV
          echo "DASHBOARD_CLIENT_SECRET=dev-secret" >> $GITHUB_ENV
          docker compose up -d postgres redis pgcat pgcat-config

      - name: Docker Compose up (apps)
        run: |
          docker compose up -d identity dashboard db storage gateway

      - name: Wait for readiness (gateway)
        run: |
          for i in {1..50}; do
            if curl -fsS http://127.0.0.1:8080/health/ready >/dev/null; then
              echo "Gateway ready"; break; fi; sleep 3; done
          curl -fsS http://127.0.0.1:8080/identity/.well-known/openid-configuration >/dev/null

      - name: Install Playwright browsers
        run: |
          dotnet build ./TansuCloud.sln -c Debug
          pwsh -NoProfile -Command "& { Set-Location tests/TansuCloud.E2E.Tests; npx playwright install chromium }"

      - name: Run AdminRateLimits UI E2E (headless)
        env:
          PW_HEADFUL: '0'
          GATEWAY_BASE_URL: 'http://127.0.0.1:8080'
        run: |
          dotnet test ./tests/TansuCloud.E2E.Tests/TansuCloud.E2E.Tests.csproj -c Debug --filter FullyQualifiedName~TansuCloud.E2E.Tests.AdminRateLimitsUiE2E
        continue-on-error: true
        id: run_tests

      - name: Collect gateway logs
        if: always()
        run: |
          mkdir -p test-results
          docker compose logs gateway > test-results/gateway-logs.txt || true

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-e2e-artifacts
          path: |
            test-results/**
            **/pw-*.png
            **/pw-*.html
            **/pw-*.zip

      - name: Fail if tests failed
        if: steps.run_tests.outcome != 'success'
        run: |
          echo "UI E2E failed. See artifacts for screenshots/HTML and gateway logs." >&2
          exit 1
